version: 2

jobs:

  test:
    working_directory: /go/src/github.com/FactomProject/factomd
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    steps:
      - checkout

      - run:
          name: Get the dependencies
          command: |
              go mod download
      - run:
          name: Build and install the executable
          command: |
              ./build.sh
      - run:
          name: Run Tests!
          no_output_timeout: 2400
          command: |
              ./test.sh short
      - run:
          name: Gofmt test
          no_output_timeout: 60
          command: |
              ./test.sh gofmt


workflows:
  version: 2
  commit-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
